[build]
    functions = "functions"

[[plugins]]
  package = "@netlify/plugin-emails"

[[redirects]]
    from="/makeAppointment"
    to="/.netlify/functions/hello"
    status=200

[functions]
  node_bundler = "esbuild"